# Generated by Django 4.2.2 on 2023-06-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_userprofile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
