# Generated by Django 4.2.2 on 2023-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('mobile_no', models.PositiveIntegerField(null=True)),
                ('email_id', models.EmailField(max_length=254, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('order_item', models.CharField(max_length=255, null=True)),
                ('order_restaurant', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Table',
                'db_table': 'data_table',
            },
        ),
    ]
