# Generated by Django 4.2.2 on 2023-06-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
