# Generated by Django 4.2.2 on 2023-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alter_datatable_mobile_no_alter_datatable_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='mobile_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='pincode',
            field=models.BigIntegerField(null=True),
        ),
    ]
