# Generated by Django 4.2.2 on 2023-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('logouttime', models.DateTimeField(null=True)),
                ('IP', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'User Login Histories',
                'db_table': 'user_login_history',
            },
        ),
    ]
